import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";
import { PUBLIC_DOB_MASKING } from "@/utils/featureFlags";
import { safeSelectPlayersByTournament } from "@/utils/safeSelectPlayers";
import { type ExportColumn, filterEmptyColumns, formatExportValue } from "@/utils/exportColumns";

const LOG_PREFIX = "[export.print]";

export function escapeHtml(value: unknown): string {
  const str = String(value ?? "");
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function maskDobForPublic(
  dob?: string | null,
  mask: boolean = PUBLIC_DOB_MASKING
): string {
  if (!dob) return "--";
  if (!mask) return dob;

  const [year, month] = dob.split("-");
  if (!year) return "--";

  const safeMonth = month && month !== "00" ? month : "--";
  return `${year}-${safeMonth}`;
}

type TournamentMeta = Pick<
  Database["public"]["Tables"]["tournaments"]["Row"],
  "title" | "city" | "start_date" | "end_date"
>;

type PlayerRow = Pick<
  Database["public"]["Tables"]["players"]["Row"],
  "rank" | "name" | "rating" | "dob" | "gender" | "state" | "city" | "club"
> & {
  federation?: string | null;
};

export type WinnersExportRow = {
  category: string;
  prizePlace: number | string | null;
  playerName: string;
  playerRank: number | string | null;
  amount: number | string | null;
  trophy: boolean | null;
  medal: boolean | null;
  typeLabel?: string | null;
  groupLabel?: string | null;
};

function formatDateRange(meta: Partial<TournamentMeta>): string {
  const range = [meta.start_date, meta.end_date].filter(Boolean).join(" – ");
  return range;
}

function formatGeneratedAt(date: Date): string {
  return date.toLocaleString("en-IN", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit"
  });
}

function buildTableRows(rows: PlayerRow[], maskDob: boolean): string {
  return rows
    .map(row => {
      const cells: Array<string | number | null | undefined> = [
        row.rank,
        row.name,
        row.rating,
        maskDobForPublic(row.dob, maskDob),
        row.gender,
        row.state || "—",
        row.city || "—",
        row.club || "—",
        row.federation || "—"
      ];

      return `<tr>${cells
        .map(value => `<td>${escapeHtml(value)}</td>`)
        .join("")}</tr>`;
    })
    .join("");
}

export function buildPlayersPrintHtml(
  meta: Partial<TournamentMeta> | null,
  rows: PlayerRow[],
  opts: { maskDob?: boolean } = {}
): string {
  const title = escapeHtml(meta?.title ?? "Tournament Players");
  const city = escapeHtml(meta?.city ?? "");
  const dateRange = escapeHtml(formatDateRange(meta ?? {}));
  const generatedAt = escapeHtml(formatGeneratedAt(new Date()));
  const maskDob = opts.maskDob ?? true;
  const totalPlayers = rows.length;
  const tableRows = buildTableRows(rows, maskDob);

  return `<!doctype html><html><head><meta charset="utf-8" />
<title>${title} — Players Export</title>
<style>
  :root { color-scheme: light; }
  @media print {
    body { margin: 0; }
  }
  body {
    margin: 0;
    font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
    color: #0f172a;
    background: #ffffff;
  }
  .page {
    width: 210mm;
    margin: 12mm auto;
    padding: 0 8mm 12mm;
  }
  header {
    margin-bottom: 12mm;
  }
  h1 {
    margin: 0 0 4mm;
    font-size: 18px;
    line-height: 1.3;
  }
  .meta {
    margin: 0;
    font-size: 12px;
    color: #475569;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    table-layout: fixed;
  }
  thead {
    display: table-header-group;
    background: #f1f5f9;
  }
  th, td {
    padding: 6px 8px;
    border-bottom: 1px solid #e2e8f0;
    font-size: 12px;
    text-align: left;
    word-break: break-word;
  }
  th {
    font-weight: 600;
    color: #1e293b;
  }
  tbody tr:nth-child(even) {
    background: #f8fafc;
  }
  tbody tr {
    page-break-inside: avoid;
  }
  footer {
    margin-top: 12mm;
    font-size: 11px;
    color: #64748b;
  }
</style>
</head><body>
  <div class="page">
    <header>
      <h1>${title} — Players</h1>
      <p class="meta">
        ${city}${city && dateRange ? " • " : ""}${dateRange}${
    dateRange ? " • " : ""
  }Generated ${generatedAt} • Total Players: ${totalPlayers}
      </p>
    </header>
    <main>
      <table>
        <thead>
          <tr>
            <th>Rank</th>
            <th>Name</th>
            <th>Rating</th>
            <th>DOB</th>
            <th>Gender</th>
            <th>State</th>
            <th>City</th>
            <th>Club</th>
            <th>Federation</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
    </main>
    <footer>
      Generated by Prize-Manager • DOB masked to yyyy-mm${maskDob ? "" : " (masking disabled)"}
    </footer>
  </div>
</body></html>`;
}

function buildTableHtml<T>(rows: T[], columns: ExportColumn<T>[]): string {
  const visibleColumns = filterEmptyColumns(rows, columns);
  const headerRow = visibleColumns.map(col => `<th>${escapeHtml(col.label)}</th>`).join("");
  const bodyRows = rows
    .map(row => {
      const cells = visibleColumns
        .map(col => `<td>${escapeHtml(formatExportValue(col.value(row)))}</td>`)
        .join("");
      return `<tr>${cells}</tr>`;
    })
    .join("");

  return `<table>
    <thead>
      <tr>${headerRow}</tr>
    </thead>
    <tbody>
      ${bodyRows}
    </tbody>
  </table>`;
}

export function getWinnersExportColumns(): ExportColumn<WinnersExportRow>[] {
  return [
    { key: "category", label: "Category", value: row => row.category },
    { key: "prizePlace", label: "Prize Place", value: row => row.prizePlace },
    { key: "playerRank", label: "Rank", value: row => row.playerRank },
    { key: "playerName", label: "Player", value: row => row.playerName },
    { key: "amount", label: "Amount", value: row => row.amount },
    { key: "trophy", label: "Trophy", value: row => row.trophy },
    { key: "medal", label: "Medal", value: row => row.medal },
    { key: "typeLabel", label: "Type", value: row => row.typeLabel },
    { key: "groupLabel", label: "Group", value: row => row.groupLabel },
  ];
}

export function buildWinnersPrintHtml(
  meta: Partial<TournamentMeta> | null,
  rows: WinnersExportRow[],
  columns: ExportColumn<WinnersExportRow>[] = getWinnersExportColumns()
): string {
  const title = escapeHtml(meta?.title ?? "Tournament Winners");
  const city = escapeHtml(meta?.city ?? "");
  const dateRange = escapeHtml(formatDateRange(meta ?? {}));
  const generatedAt = escapeHtml(formatGeneratedAt(new Date()));
  const totalWinners = rows.length;

  const tableHtml = buildTableHtml(rows, columns);

  return `<!doctype html><html><head><meta charset="utf-8" />
<title>${title} — Winners Export</title>
<style>
  :root { color-scheme: light; }
  @media print {
    body { margin: 0; }
  }
  body {
    margin: 0;
    font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
    color: #0f172a;
    background: #ffffff;
  }
  .page {
    width: 210mm;
    margin: 12mm auto;
    padding: 0 8mm 12mm;
  }
  header {
    margin-bottom: 12mm;
  }
  h1 {
    margin: 0 0 4mm;
    font-size: 18px;
    line-height: 1.3;
  }
  .meta {
    margin: 0;
    font-size: 12px;
    color: #475569;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    table-layout: fixed;
  }
  thead {
    display: table-header-group;
    background: #f1f5f9;
  }
  th, td {
    padding: 6px 8px;
    border-bottom: 1px solid #e2e8f0;
    font-size: 12px;
    text-align: left;
    word-break: break-word;
  }
  th {
    font-weight: 600;
    color: #1e293b;
  }
  tbody tr:nth-child(even) {
    background: #f8fafc;
  }
  tbody tr {
    page-break-inside: avoid;
  }
  footer {
    margin-top: 12mm;
    font-size: 11px;
    color: #64748b;
  }
</style>
</head><body>
  <div class="page">
    <header>
      <h1>${title} — Winners</h1>
      <p class="meta">
        ${city}${city && dateRange ? " • " : ""}${dateRange}${
    dateRange ? " • " : ""
  }Generated ${generatedAt} • Total Winners: ${totalWinners}
      </p>
    </header>
    <main>
      ${tableHtml}
    </main>
    <footer>
      Generated by Prize-Manager • Winners grouped by category order
    </footer>
  </div>
</body></html>`;
}

export function openPrintWindow(html: string, filenameBase = "players-export"): boolean {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    return false;
  }

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.document.title = filenameBase;

  setTimeout(() => {
    try {
      printWindow.focus();
      printWindow.print();
    } catch (error) {
      console.error(`${LOG_PREFIX} print failed`, error);
    }
  }, 75);

  return true;
}

export async function exportPlayersViaPrint({
  tournamentId,
  maskDob = PUBLIC_DOB_MASKING
}: {
  tournamentId: string;
  maskDob?: boolean;
}) {
  const start = performance.now();
  console.log(`${LOG_PREFIX} start tournament=${tournamentId} version=players-summary`);

  try {
    const { data: tournament, error: tournamentError } = await supabase
      .from("tournaments")
      .select("title, city, start_date, end_date")
      .eq("id", tournamentId)
      .maybeSingle();

    if (tournamentError) {
      throw tournamentError;
    }

    const { data: players, count, usedColumns } = await safeSelectPlayersByTournament(
      tournamentId,
      ['rank', 'name', 'rating', 'dob', 'gender', 'state', 'city', 'club', 'federation'],
      { column: 'rank', ascending: true }
    );

    if (!players || players.length === 0) {
      throw new Error('No players found for this tournament');
    }

    console.log('[print] Loaded players for print', { count, usedColumns });

    const html = buildPlayersPrintHtml(tournament ?? null, players as PlayerRow[], { maskDob });
    const opened = openPrintWindow(html, `players-${tournamentId}`);

    if (!opened) {
      throw new Error("Popup blocked. Allow popups to print or save as PDF.");
    }

    const duration = Math.round(performance.now() - start);
    console.log(`${LOG_PREFIX} ok tournament=${tournamentId} duration_ms=${duration}`);
  } catch (error: unknown) {
    const duration = Math.round(performance.now() - start);
    const message = error instanceof Error ? error.message : String(error);
    console.error(`${LOG_PREFIX} error tournament=${tournamentId} message=${message}`);
    console.log(`${LOG_PREFIX} error duration_ms=${duration}`);
    throw error;
  }
}
