import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";
import { PUBLIC_DOB_MASKING } from "@/utils/featureFlags";
import { maskDobForPublic } from "@/utils/print";

const LOG_PREFIX = "[export.pdf]";

type PlayersRow = Pick<
  Database["public"]["Tables"]["players"]["Row"],
  "rank" | "name" | "rating" | "dob" | "gender" | "state" | "city" | "club"
>;

type TournamentMeta = Pick<
  Database["public"]["Tables"]["tournaments"]["Row"],
  "title" | "city" | "start_date" | "end_date"
>;

function ensureClient(client?: SupabaseClient<Database>) {
  return client ?? supabase;
}

export async function downloadPlayersPdf({
  tournamentId,
  maskDob = PUBLIC_DOB_MASKING,
  client
}: {
  tournamentId: string;
  maskDob?: boolean;
  client?: SupabaseClient<Database>;
}) {
  console.log(`${LOG_PREFIX} start tournament=${tournamentId} version=players-summary`);

  let renderer: any;
  try {
    const moduleId = '@react-pdf/renderer';
    renderer = await import(/* @vite-ignore */ moduleId);
  } catch (error) {
    console.error(`${LOG_PREFIX} error tournament=${tournamentId} message=react-pdf-unavailable`, error);
    throw new Error("React-PDF not available in this environment");
  }

  const db = ensureClient(client);

  const { data: tournament, error: tournamentError } = await db
    .from("tournaments")
    .select("title, city, start_date, end_date")
    .eq("id", tournamentId)
    .maybeSingle();
  if (tournamentError) {
    console.error(`${LOG_PREFIX} error tournament=${tournamentId} message=${tournamentError.message}`);
    throw tournamentError;
  }

  const { data: players, error: playersError } = await db
    .from("players")
    .select("rank, name, rating, dob, gender, state, city, club")
    .eq("tournament_id", tournamentId)
    .order("rank", { ascending: true });
  if (playersError) {
    console.error(`${LOG_PREFIX} error tournament=${tournamentId} message=${playersError.message}`);
    throw playersError;
  }

  const { Document, Page, Text, View, StyleSheet, pdf } = renderer;

  const styles = StyleSheet.create({
    page: {
      padding: 32,
      fontSize: 10,
      fontFamily: "Helvetica",
      color: "#1f2937"
    },
    header: {
      marginBottom: 16
    },
    title: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 4
    },
    subtitle: {
      fontSize: 10,
      color: "#4b5563"
    },
    tableHeader: {
      flexDirection: "row",
      backgroundColor: "#f9fafb",
      borderBottomWidth: 1,
      borderColor: "#d1d5db",
      paddingVertical: 6,
      paddingHorizontal: 8
    },
    tableRow: {
      flexDirection: "row",
      borderBottomWidth: 0.5,
      borderColor: "#e5e7eb",
      paddingVertical: 6,
      paddingHorizontal: 8
    },
    cell: {
      flexGrow: 1,
      paddingRight: 6
    },
    cellSmall: {
      width: "10%"
    },
    cellMedium: {
      width: "15%"
    },
    cellLarge: {
      width: "25%"
    }
  });

  const formatRange = (meta: TournamentMeta | null) => {
    if (!meta) return "";
    const parts = [
      meta.city,
      meta.start_date && meta.end_date
        ? `${meta.start_date} – ${meta.end_date}`
        : meta.start_date
    ];
    return parts.filter(Boolean).join(" • ");
  };

  const headerCells = [
    { label: "Rank", width: styles.cellSmall },
    { label: "Name", width: styles.cellLarge },
    { label: "Rating", width: styles.cellSmall },
    { label: "DOB", width: styles.cellMedium },
    { label: "Gender", width: styles.cellSmall },
    { label: "State", width: styles.cellSmall },
    { label: "City", width: styles.cellSmall },
    { label: "Club", width: styles.cellMedium }
  ];

  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{(tournament?.title ?? "Tournament Players") + " — Players"}</Text>
          <Text style={styles.subtitle}>
            {formatRange(tournament)} • Total Players: {(players ?? []).length}
          </Text>
          <Text style={styles.subtitle}>
            Generated by Prize-Manager • DOB masked to yyyy-mm{maskDob ? "" : " (masking disabled)"}
          </Text>
        </View>
        <View style={styles.tableHeader}>
          {headerCells.map(cell => (
            <Text key={cell.label} style={[styles.cell, cell.width, { fontWeight: "bold" }]}>
              {cell.label}
            </Text>
          ))}
        </View>
        {(players ?? []).map((player: PlayersRow, index) => (
          <View key={`${player.rank}-${index}`} style={styles.tableRow}>
            <Text style={[styles.cell, styles.cellSmall]}>{player.rank ?? ""}</Text>
            <Text style={[styles.cell, styles.cellLarge]}>{player.name}</Text>
            <Text style={[styles.cell, styles.cellSmall]}>{player.rating ?? ""}</Text>
            <Text style={[styles.cell, styles.cellMedium]}>{maskDobForPublic(player.dob, maskDob)}</Text>
            <Text style={[styles.cell, styles.cellSmall]}>{player.gender ?? ""}</Text>
            <Text style={[styles.cell, styles.cellSmall]}>{player.state ?? ""}</Text>
            <Text style={[styles.cell, styles.cellSmall]}>{player.city ?? ""}</Text>
            <Text style={[styles.cell, styles.cellMedium]}>{player.club ?? ""}</Text>
          </View>
        ))}
      </Page>
    </Document>
  );

  const blob = await pdf(doc).toBlob();
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  const safeTitle = (tournament?.title ?? "tournament").replace(/[^a-z0-9-_]+/gi, "-");
  link.download = `players-${safeTitle}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

  console.log(`${LOG_PREFIX} ok tournament=${tournamentId}`);
}
